dist: bionic
language: cpp
compiler: gcc
cache: ccache

branches:
  only:
    - master
    - master_coverity_scan
    - /^stable-.*$/

os:
  - linux

before_install:
  - eval "${MATRIX_EVAL}"
  - test ! -f /opt/qt512/bin/qt512-env.sh || source /opt/qt512/bin/qt512-env.sh
  - ./tests/scripts/install-sword.sh -j2
  - export LD_LIBRARY_PATH=${HOME}/local/lib:$LD_LIBRARY_PATH

script:
  - if [ "0${COVERITY_SCAN_BRANCH}" != "01" ]; then mkdir b && cd b && cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/local && make -j2 && make install; fi

env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
     - secure: "FmufrIN8L4Ptfbn0Lw/1S7fKnPxpvv7t9KEN5XhQ3lwW5Qir7mGe2r87biaKyjo15VNc4bizA2wR63YUXz6JPMETwYPahKSlW2tAsHmJTOwyweNW7zkKf6Iwrf9vYaMZyOpR2jRkD9Ko8vd4BpIw4FF6X/vaJqfnvQyIOiDGFr8="


matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc
            - g++
            - cmake
            - libclucene-dev
            - libqt5svg5-dev
            - libqt5xmlpatterns5-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qtdeclarative5-dev
            - qttools5-dev-tools
            - qtwebengine5-dev
      env:
        - MATRIX_EVAL="CC=gcc CXX=g++"
    - addons:
        apt:
          packages:
            - clang
            - cmake
            - libclucene-dev
            - libqt5svg5-dev
            - libqt5xmlpatterns5-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qtdeclarative5-dev
            - qttools5-dev-tools
            - qtwebengine5-dev
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
    - addons:
        apt:
          sources:
            - sourceline: ppa:beineri/opt-qt-5.12.6-bionic
          packages:
            - gcc
            - g++
            - cmake
            - libclucene-dev
            - libglvnd-dev
            - mesa-common-dev
            - qt512base
            - qt512declarative
            - qt512svg
            - qt512webengine
            - qt512xmlpatterns
            - qt512tools
      env:
        - MATRIX_EVAL="CC=gcc CXX=g++"
    - addons:
        apt:
          sources:
            - sourceline: ppa:beineri/opt-qt-5.12.6-bionic
          packages:
            - clang
            - cmake
            - libclucene-dev
            - libglvnd-dev
            - mesa-common-dev
            - qt512base
            - qt512declarative
            - qt512svg
            - qt512webengine
            - qt512xmlpatterns
            - qt512tools
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
    - addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:beineri/opt-qt-5.12.6-bionic
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libclucene-dev
            - libglvnd-dev
            - mesa-common-dev
            - qt512base
            - qt512declarative
            - qt512svg
            - qt512webengine
            - qt512xmlpatterns
            - qt512tools
      env:
        - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
    - addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:beineri/opt-qt-5.12.6-bionic
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libclucene-dev
            - libglvnd-dev
            - mesa-common-dev
            - qt512base
            - qt512declarative
            - qt512svg
            - qt512webengine
            - qt512xmlpatterns
            - qt512tools
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
    - addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - llvm-toolchain-bionic-8
            - sourceline: ppa:beineri/opt-qt-5.12.6-bionic
          packages:
            - clang-8.0
            - llvm-8.0-dev
            - cmake
            - libclucene-dev
            - libglvnd-dev
            - mesa-common-dev
            - qt512base
            - qt512declarative
            - qt512svg
            - qt512webengine
            - qt512xmlpatterns
            - qt512tools
      env:
        - MATRIX_EVAL="CC=clang-8.0 CXX=clang++-8.0"

addons:
  coverity_scan:
    project:
      name: "bibletime/bibletime"
      description: "BibleTime build submitted via Travis CI"
    notification_email: bibletime-coverity@heh.ee
    build_command_prepend: "mkdir b && cd b && cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/local/"
    build_command: "cmake --build ."
    branch_pattern: .*_coverity_scan

notifications:
  irc: "chat.freenode.net#bibletime"
